services:
  service-sante:
    image: service-sante
    container_name: service-sante
    restart: always
    build: .
    ports:
      - 5010:5010
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1


